# CHANGEME: Set these variable to your liking
title: myESPhome projects
description: Powered by ESPHome and ESP Web Tools
#theme: jekyll-theme-slate
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one